### ISSUE TITLE
Compatible with Si4464

### ISSUE THREAD

**Issue by techmike78** [on1arf/pocsag#4]
Good day.
Will the library be compatible for working with si4464, can it be possible to send a session using the data model from rf22?
The question arose because of the presence of motorola avisor on 157 MHz.

**Comment by on1arf** [comment]
Hi,

"try it out", I would propose :-)

The pocsag-library uses the "[radiohead](http://www.airspayce.com/mikem/arduino/RadioHead/index.html)" library for controlling the radio-chips.

The si4464 is mentioned as one of the supported chips so it should work.



Kristoff
